# Generated by Django 5.1.4 on 2024-12-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="action",
        ),
        migrations.AlterField(
            model_name="habit",
            name="name",
            field=models.CharField(max_length=150, verbose_name="название привычки"),
        ),
    ]
