# Generated by Django 5.1.4 on 2024-12-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_remove_habit_action_alter_habit_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="name",
        ),
        migrations.AddField(
            model_name="habit",
            name="action",
            field=models.CharField(default=1, max_length=150, verbose_name="действие"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="habit",
            name="execution_time",
            field=models.TimeField(verbose_name="время на выполнение"),
        ),
    ]
